version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: telegram_messages

models:
  - name: stg_telegram_messages
    description: "Staging model that cleanses and standardizes raw Telegram data imports."
    columns:
      - name: surrogate_key
        tests:
          - unique
          - not_null